# Generated by Django 5.0.3 on 2024-05-01 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_custom_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registation_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
