# Generated by Django 5.0.3 on 2024-05-01 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_registrationrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
