# Generated by Django 5.0.3 on 2024-05-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
