# Generated by Django 5.0.3 on 2024-04-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UnsavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='unsaved_item_images/')),
            ],
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='saved_images/')),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField(default=False)),
                ('unsaved_image', models.ImageField(blank=True, null=True, upload_to='unsaved_item_images/')),
                ('saved_image', models.ImageField(blank=True, null=True, upload_to='saved_item_images/')),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.todolist')),
            ],
        ),
    ]
