# Generated by Django 5.0.3 on 2024-04-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_alter_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'List'},
        ),
    ]
