# Generated by Django 5.0.3 on 2024-04-19 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_rename_todolist_item_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='saved_image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unsaved_image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.item')),
            ],
        ),
    ]
