# Generated by Django 5.0.3 on 2024-04-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_remove_item_saved_image_remove_item_unsaved_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveditem',
            old_name='todolist',
            new_name='list',
        ),
    ]
