# Generated by Django 5.0.3 on 2024-04-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_rename_todolist_saveditem_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveditem',
            old_name='list',
            new_name='lists',
        ),
    ]
