# Generated by Django 5.0.3 on 2024-04-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_item_image_alter_image_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemDes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemRentalPeriod',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemType',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='itemDes',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='itemName',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='itemRentalPeriod',
        ),
        migrations.RemoveField(
            model_name='saveditem',
            name='itemType',
        ),
        migrations.RemoveField(
            model_name='unsaveditem',
            name='itemDes',
        ),
        migrations.RemoveField(
            model_name='unsaveditem',
            name='itemName',
        ),
        migrations.RemoveField(
            model_name='unsaveditem',
            name='itemRentalPeriod',
        ),
        migrations.RemoveField(
            model_name='unsaveditem',
            name='itemType',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='rental_period',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='rental_period',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='unsaveditem',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='unsaveditem',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unsaveditem',
            name='rental_period',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='unsaveditem',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Booking.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Booking.todolist'),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='Booking.todolist'),
        ),
    ]
