# Generated by Django 5.0.3 on 2024-05-01 13:04

import Booking.models
import django.db.models.deletion
import django_resized.forms
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_remove_item_itemdes_remove_item_itemname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rental_period',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'right'], default='', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 245], upload_to='Item_img/', verbose_name=Booking.models.Image),
        ),
        migrations.AddField(
            model_name='item',
            name='period',
            field=models.CharField(default='1 Week', max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.todolist'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateTimeField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Booking.category'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_cropping.fields.ImageCropField(blank=True, default='avatar.png', upload_to='profile_pics')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='Image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='item_images'),
        ),
    ]
