# Generated by Django 5.0.3 on 2024-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_category_remove_image_image_remove_item_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profiles'},
        ),
    ]
