# Generated by Django 5.0.3 on 2024-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0013_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profile'},
        ),
    ]
