# Generated by Django 5.0.3 on 2024-05-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0014_alter_profile_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
