# Generated by Django 5.0.3 on 2024-05-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0016_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
