# Generated by Django 5.0.3 on 2024-05-02 08:53

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0017_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'right'], default='', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 245], upload_to='Item_img/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='lists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Booking.todolist'),
        ),
    ]
