# Generated by Django 5.0.3 on 2024-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0018_alter_item_img_alter_item_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
