# Generated by Django 5.0.3 on 2024-05-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0019_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Booking.category'),
        ),
    ]
