# Generated by Django 5.0.3 on 2024-05-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0020_bookingitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='category',
        ),
    ]
