# Generated by Django 5.0.3 on 2024-05-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0024_alter_bookingitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Booking.category'),
        ),
    ]
