# Generated by Django 5.0.3 on 2024-05-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0026_unsaveditem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsaveditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='BookingItem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
