# Generated by Django 5.0.3 on 2024-05-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0027_remove_unsaveditem_category_remove_item_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Booking.item'),
        ),
    ]
