# Generated by Django 5.0.3 on 2024-05-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0030_remove_item_category_item_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Category'},
        ),
    ]
