# Generated by Django 5.0.3 on 2024-05-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0032_rename_todolist_category_rename_lists_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsaveditem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unsaved_items', to='Booking.category'),
            preserve_default=False,
        ),
    ]
