# Generated by Django 5.0.3 on 2024-05-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0033_unsaveditem_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ToDoList',
        ),
    ]
