# Generated by Django 5.0.3 on 2024-05-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0034_rename_category_todolist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'List'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='lists',
        ),
        migrations.RenameField(
            model_name='saveditem',
            old_name='category',
            new_name='lists',
        ),
        migrations.RemoveField(
            model_name='unsaveditem',
            name='category',
        ),
    ]
