# Generated by Django 5.0.3 on 2024-05-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0035_alter_todolist_options_rename_category_item_lists_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lists',
            new_name='list',
        ),
    ]
