# Generated by Django 5.0.6 on 2024-06-23 16:35

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0037_alter_item_image_alter_saveditem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'right'], default='', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 245], upload_to='Item_img/'),
        ),
        migrations.AlterField(
            model_name='saveditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='saved_images/'),
        ),
        migrations.AlterField(
            model_name='unsaveditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='unsaved_item_images/'),
        ),
    ]
